### ISSUE TITLE
nc_writer able to write metadata

### ISSUE THREAD

**Issue by flampouris** [JCSDA/ioda-converters#100]
Currently, it is impossible to write metadata into the nc ioda compatible files.

**Comment by CoryMartin-NOAA** [comment]
I'm also encountering this issue as I work on Issue #107 . I have a working solution that I'll push soon to feature/gsi_ncwriter but am open to changing it for a more permanent/better solution.

**Comment by srherbener** [comment]
@CoryMartin-NOAA, @flampouris, is this issue resolved? Thanks

**Comment by CoryMartin-NOAA** [comment]
@srherbener I think so (or at least the GSI ncdiag writers are able to write metadata), will wait for Stelios to confirm this is the case for the marine converters too.
