### ISSUE TITLE
NcWriter NetCDF format

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA/ioda-converters#133]
Using NETCDF4 as the format produces what I assume are long integers (ncdump -h shows something like 8955L for nlocs) whereas using NETCDF4_CLASSIC uses standard integers (nlocs = 8955). Does it matter which one is used? It seems that UFO tests fail when geoval files have L in the date_time attribute. If there is a check in Fortran code that looks for NF90_INT, we need to make sure the attributes being written are INT and not LONG.

**Comment by srherbener** [comment]
Looking at the netcdf website, it looks like the differences between NETCDF4 and NETCDF4_CLASSIC are that NETCDF4 has Groups and User defined data types whereas NETCDF4_CLASSIC does not have those two features. Here is a link to that information:
* https://www.unidata.ucar.edu/software/netcdf/workshops/2008/netcdf4/Nc4DataModel.html

We aren't using these features now, but we may want to use groups in the future to help organize data. Keeping with NETCDF4 format allows compatibility with HDF5, and consequently scripts and programs written using the HDF5 API. This might be important when it comes to diagnostic/plotting tools, but I'm not sure about that. I think it would good if we can keep the NETCDF4 format and fix the int vs long issue in another manner. 

I tried some experiments and discovered that Numpy allows you to control the precision of intergers and floating point numbers, and the NETCDF4 api will store these accordingly. For example
~~~~~~~
DateTime = numpy.int32(2018041500)
...
nc.setncattr("date_time", DateTime)
~~~~~~~
will store the DateTime value as a 32-bit integer which should satisfy the netcdf Fortran API.

I would like to see if we can fix this issue by using the numpy method as show above. Could you send me a test case so I could try this out?

Thanks!

**Comment by CoryMartin-NOAA** [comment]
I just tried it and yes, for example in ioda_conv_ncio line 217 changing it to:
self._fid.setncattr("date_time", np.int32(refDateTime))
seems to have worked (at least the L is now missing when using ncdump)

I can add this in as part of my existing pull request.

**Comment by srherbener** [comment]
Sounds great! Thanks for doing this.
