### ISSUE TITLE
Add additional fields to GSI diag files

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA/ioda-converters#137]
See Google Sheet for details.

**Comment by CoryMartin-NOAA** [comment]
Obs Metadata:
FOV number
Scan line number
GeoVaLS:
tropopause height
PBL height

**Comment by srherbener** [comment]
@CoryMartin-NOAA, is this resolved now? Thanks!

**Comment by CoryMartin-NOAA** [comment]
@srherbener for now I think so but as things like QC filters and other operators start to be worked on, there may be a need for additional output fields. I'd say keep it open until at least the code sprint in August.

**Comment by srherbener** [comment]
@CoryMartin-NOAA, if all the needs that we are aware of today are met, I would prefer to close this and open new issues if and when we become aware of additional meta data that is required. That way we don't become complacent about an issue that has been open for a long time. Does this sound okay?

**Comment by CoryMartin-NOAA** [comment]
@srherbener that works, and in the future, probably better anyways if it's a specific issue like "GSI diags need X". Closed.
