### ISSUE TITLE
Difference in ioda input files in attrubutes and for every variable - nccmp fails

### ISSUE THREAD

**Issue by ShastriPaturi** [JCSDA/ioda-converters#150]
The nccmp fails for all the ioda-converter tests. I am including the a portion of the output for goade_ship.nc:
12: Test command: /scratch3/NCEPDEV/marine/save/Shastri.Paturi/Jedi-QC-CS-04-2019/soca-bundle/build/ioda-converters/test/iodaconv_comp.sh "/scratch3/NCEPDEV/marine/save/Shastri.Paturi/Jedi-QC-CS-04-2019/soca-bundle/build/bin/godae_ship2ioda.py
                       -i testinput/godae_ship.bin
                       -o testrun/godae_ship.nc
                       -d 1998090112" "godae_ship.nc"
12: Environment variables:
12:  OMP_NUM_THREADS=1
12: Test timeout computed to be: 9.99988e+06
12:     number ship obs: 1085
12:   max number levels: 1
12: file version number: 1
12: verify ob_sign for version = 1
12: DIFFER : LENGTHS OF GLOBAL ATTRIBUTE : _NCProperties : 55 <> 57 : VALUES : version=1|netcdflibversion=4.6.1|hdf5libversion=1.10.2 <> version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.8.18
12: DIFFER : VARIABLE : sea_surface_temperature@ObsValue : POSITION : [0] : VALUES : -0.300006 <> 27.6
12: DIFFER : VARIABLE : sea_surface_temperature@ObsValue : POSITION : [1] : VALUES : 22.5 <> 28.8
12: DIFFER : VARIABLE : sea_surface_temperature@ObsValue : POSITION : [2] : VALUES : 22.8 <> 29.2
12: DIFFER : VARIABLE : sea_surface_temperature@ObsValue : POSITION : [3] : VALUES : 18.6 <> 6.19999
12: DIFFER : VARIABLE : sea_surface_temperature@ObsValue : POSITION : [4] : VALUES : 18.9 <> 7.50001
12: DIFFER : VARIABLE : sea_surface_temperature@ObsValue : POSITION : [5] : VALUES : -0.300006 <> 27.6
12: DIFFER : VARIABLE : sea_surface_temperature@ObsValue : POSITION : [6] : VALUES : -1.30001 <> 19.4
12: DIFFER : VARIABLE : sea_surface_temperature@ObsValue : POSITION : [7] : VALUES : 14.1 <> 26.5
12: DIFFER : VARIABLE : sea_surface_temperature@ObsValue : POSITION : [8] : VALUES : 23.4 <> 18.6
12: DIFFER : VARIABLE : sea_surface_temperature@ObsValue : POSITION : [9] : VALUES : 21.6 <> 8.40001

Every ATTRIBUTE and VARIABLE values differ

**Comment by flampouris** [comment]
I have the same issues since Friday. Is there any specific configuration or compilation flags for nccmp?

Thank you!

**Comment by travissluka** [comment]
... working on it

**Comment by travissluka** [comment]
@ShastriPaturi out of curiosity, what is the version of nccmp on Theia (`nccmp -V`)

**Comment by ShastriPaturi** [comment]
1.8.2.0

**Comment by travissluka** [comment]
ah, ok, the latest version is 1.8.5.0, and with that version nccmp doesn't seem to be trying to do the comparisons for the hidden variables (e.g. `_NCProperties`). I'll still push a change so that those variables are ignored and so should work with your version of nccmp

**Comment by srherbener** [comment]
Hi all, is this issue resolved now? Thanks

**Comment by srherbener** [comment]
@ShastriPaturi, @flampouris is this issue resolved? Thanks

**Comment by srherbener** [comment]
Since I haven't heard for a long time, I'm going to close this issue. If there is still a problem, please open a new issue and we will get that addressed. Thanks!
