### ISSUE TITLE
NcWriter changing order of observations

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA/ioda-converters#152]
@louiskouvaris noticed that the sbuv ozone profiles no longer are in sequential order. The GSI diag files are in order, profile by profile, but after writing out the obs for IODA, they are seemingly in random order. I've traced this issue to be that somehow NcWriter is changing the order of the observations. This probably is not ideal but I don't know if it's a showstopper except for how to subset the obs.

**Comment by CoryMartin-NOAA** [comment]
This is an issue with defaultdict vs OrderedDict. Defaultdict does not preserve the order in which the observations are placed into the dictionary when it's later iterated over, but I do not yet know how to replace defaultdict(lamda ... with OrderedDict in the converter scripts (not necessarily a problem in NcWriter but the places where it's called)

**Comment by CoryMartin-NOAA** [comment]
https://stackoverflow.com/questions/6190331/can-i-do-an-ordered-default-dict-in-python

This shows how to create an ordered, default dict, which is what's needed to fix this issue. Works on Theia on Python2.7 and Python 3.5

**Comment by svahl991** [comment]
I've seen this random-order effect happen as well when converting obs files. I guess my thought is that if the sequence of the obs is important for some purposes, then we should indicate the sequence with a value in the metadata, rather than have it only be captured by the storage sequence in the netCDF file. I know the concept of using "records" for data subsetting has always been part of the IODA plan, although it hasn't been used very much so far that I've seen. So each profile would have its own record_number@MetaData value. ("record_number" is a special string specified in the NcWriter code.) @srherbener knows more about how record_number should be used than I do.

**Comment by CoryMartin-NOAA** [comment]
@svahl991 I agree, that my solution of just forcing the order to be the same as what comes from GSI is not idea, and there should be record_number or something to that effect used. Regardless, it's probably still better to ensure this same order as the input files for now just for debugging/diagnostic purposes even for obs that are independent of one another.

**Comment by srherbener** [comment]
My understanding is that we want the order of the observations that appear in the output of converter scripts to be repeatable to facilitate testing. The order doesn't have to follow what appears in the input file, it just has to be the same order every time you run the script with the same input.

The record number is for a different purpose which is to identify "atomic" units of which should not be broken apart when distributing obs across multiple process elements. An example of a record is a single radiosonde sounding. Note that a single record can consist of multiple locations.

## For testing:
The NcWriter code is using OrderedDict when creating a new dictionary (eg, ExtractObsData method). The marine scripts are using defaultdict and the tests seem to be working indicating that the ordering in the output files are repeatable. Perhaps it is sufficient for NcWriter to use OrderedDict and the clients of NcWriter to use defaultdict.

## For keeping profiles together:
The idea with record_number@MetaData would be to label all of the locations belonging to a single profile with a unique record_number value. The first profile would get number 1, the next number 2, etc. The elements of the record key in the dictionary are intended to be used to identify unique records from the input data. Then the ExtractObsData method numbers these for you and generates the record_number@MetaData values.

Is there a variable (or variables) in the GSI files that you mention that could be used to identify the records (profiles) that could be used in the record key tuple? If not would it be easy to generate a dummy variable for the record key?

**Comment by CoryMartin-NOAA** [comment]
@srherbener for the first point, the "OrderedDefaultDict" class that I found on StackOverflow seems to be working well, and @travissluka was planning on (or maybe he already did) implementing it for the marine converters. For the profiles, I believe we can use StationID to create the record number (at least for sondes, not sure about aircraft but I suspect there are also similar ID codes like tailnumbers). Once the current changes I've added to the gsi-ncdiag scripts are added in the pull request I can start to add in the record key and other changes to a new branch.

**Comment by travissluka** [comment]
@CoryMartin-NOAA  yes, I have a branch with the marine tests working using your ordereddefaultdict, I'll push it once your PR is merged in

**Comment by CoryMartin-NOAA** [comment]
@travissluka @srherbener I think this can be closed with the addition of OrderedDefaultDict now in place for gsi-ncdiag and marine, correct?

**Comment by srherbener** [comment]
I'm okay with closing this issue. Do you agree @travissluka?

**Comment by travissluka** [comment]
Sounds good to me
