### ISSUE TITLE
nccmp and hidden attributes

### ISSUE THREAD

**Issue by travissluka** [JCSDA/ioda-converters#156]
the script calling nccp needs to ignore useless hidden attributes such as 
`version, netcdflibversion, hdf5libversion` 

currently causing ctests to fail becuase of different netcdf/hdf5 versions on different platforms.

**Comment by srherbener** [comment]
@travissluka, is this issue resolved now? Thanks!

**Comment by travissluka** [comment]
I'm unable to recreate this behavior. Any relatively recent version of nccmp should work even if the hidden variables are different. Closing
