### ISSUE TITLE
pycode style not  found

### ISSUE THREAD

**Issue by travissluka** [JCSDA/ioda-converters#157]
when `ioda-converters` is part of a bundle, the included `pycodestyle` file is not found. Sometimes a system `pycodestyle` is used instead, which explains why in the past I had seen differences in the coding norms.

**Comment by aerorahul** [comment]
@travissluka Can you please paste the output of the 1st test?
I am interested in what you see for the variable `PYCODESTYLE_CFG_PATH`.
`ecbuild_add_test` in `CMakeLists.txt` (for each of the sub-directories) pass `${CMAKE_SOURCE_DIR}` as the argument to use that particular `pycodestyle`

```
Start 1: iodaconv_lib-python_coding_norms

1: Test command: /Users/rmahajan/Work/JEDI/build/ioda-converters/bin/lint.sh "/Users/rmahajan/Work/JEDI/src/ioda-converters/src/lib-python" "/Users/rmahajan/Work/JEDI/src/ioda-converters"
1: Environment variables:
1:  OMP_NUM_THREADS=1
1: Test timeout computed to be: 1500
1: + SRC_DIR=/Users/rmahajan/Work/JEDI/src/ioda-converters/src/lib-python
1: + PYCODESTYLE_CFG_PATH=/Users/rmahajan/Work/JEDI/src/ioda-converters
1: + cd /Users/rmahajan/Work/JEDI/src/ioda-converters/src/lib-python
1: + pycodestyle --config=/Users/rmahajan/Work/JEDI/src/ioda-converters/.pycodestyle .
1/1 Test #1: iodaconv_lib-python_coding_norms ...   Passed    0.13 sec
```

**Comment by aerorahul** [comment]
@travissluka An alternative is to hard-wire the `pycodestyle` to use the one in top-level directory, but I wanted to give the developer the option to specify there own in their converter directories.

**Comment by travissluka** [comment]
PYCODESTYLE_CFG_PATH is pointing to the root of my soca-bundle source dir

```
1: Test command: /home/tsluka/work/jedi-soca/soca.build/bin/lint.sh "/home/tsluka/work/jedi-soca/soca.src/ioda-converters/src/lib-python" "/home/tsluka/work/jedi-soca/soca.src"
1: Environment variables:
1:  OMP_NUM_THREADS=1
1: Test timeout computed to be: 9.99988e+06
1: + SRC_DIR=/home/tsluka/work/jedi-soca/soca.src/ioda-converters/src/lib-python
1: + PYCODESTYLE_CFG_PATH=/home/tsluka/work/jedi-soca/soca.src
1: + cd /home/tsluka/work/jedi-soca/soca.src/ioda-converters/src/lib-python
1: + pycodestyle --config=/home/tsluka/work/jedi-soca/soca.src/.pycodestyle .
1: ./ioda_conv_ncio.py:11:80: E501 line too long (83 > 79 characters)
1: ./ioda_conv_ncio.py:13:80: E501 line too long (83 > 79 characters)
1: ./ioda_conv_ncio.py:44:80: E501 line too long (83 > 79 characters)
```

**Comment by aerorahul** [comment]
@travissluka I see.  When IODA-converters are built inside of a bundle, `$CMAKE_SOURCE_DIR` will be the base of the bundle, and hence the norm test fails to find the correct `.pycodestyle`.
I will figure out a way to get the correct `pycodestyle` file with or without a bundle.
