### ISSUE TITLE
geovals coming from GSI: air_pressure units

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA/ioda-converters#163]
We should have air_pressure in *Pa* in the geovals files coming from GSI. This would allow to switch to using the right units inside UFO and inside getValues of the models.

**Comment by CoryMartin-NOAA** [comment]
This has been updated in feature/files_for_jedi for:

- [ ] - setupt
- [ ] - setuprad
- [ ] - setupw
- [ ] - setupps
- [ ] - setupoz

**Comment by shlyaeva** [comment]
@CoryMartin-NOAA: thanks a lot, I'll give it a try!

**Comment by CoryMartin-NOAA** [comment]
Having weird compiling issues, reopening until I can confirm it's working and produces air pressure output in Pa.
