### ISSUE TITLE
surface pressure obs file has inconsistent obs and meta data

### ISSUE THREAD

**Issue by srherbener** [JCSDA/ioda-converters#176]
The sample file from Yali named "sfc_ps_obs_2018041500.nc4" has locations where the meta data "station_elevation" has missing data but the observation data "surface_pressure" has valid data.

Some examples where this happens are:

| location number | surface pressure | station elevation |
|-----------------|------------------|------------------|
| 5642 | 988.2 | 9999 |
| 6362 | 993.6 | 9999 |
| 7459 | 854.8 | 9999 |

This may be an issue with obs operators that use the station_elevation and surface_pressure data since it might be the case that the locations with valid obs data will get used and it may not be realized that the meta data is missing.

There are two concerns with this:
* Is it problematic in UFO to have station_elevation with missing values where the corresponding obs values are not marked as missing?
* The missing mark of "9999" is not getting recognized as a missing value so it will get loaded into IODA and appear to be valid data.
    * The proper missing mark in the netcdf file is to use the netcdf "fill" value.

**Comment by YaliWu0219** [comment]
Thanks, Stephen~
How about using Domain Check? For example: 
         - Filter: Domain Check
                where:
                    - variable: altitude
                       minvalue: 0
                       maxvalue: 30000

**Comment by srherbener** [comment]
I'm not sure if that's how we want to handle these cases. Perhaps @shlyaeva and @ytremolet can shed some light on this. I need some guidance myself on how the IODA converters and IODA should handle this case.

**Comment by CoryMartin-NOAA** [comment]
I'm trying to think of a good way to handle elevation/height for the T2m operator too. It seems that for 2m temp obs, height=station_elev and not 2= height-station_elev like it should be. I'll try to add some logic to check for 9999 values and replace with fill_value as well as how to make the observation 2m agl if it's set to 0 for sfc temp/q.

**Comment by ytremolet** [comment]
I think for short term testing you can use the domain check filter but really we should have a proper missing value in the file. Let me know if we need to discuss this.

**Comment by CoryMartin-NOAA** [comment]
I now have replaced 9999 for height and elevation with the netCDF fill value, but how is that defined when using the filters? I noticed while trying to debug my T2 UFO that one of the values for height is NaN, and thus causing all subsequent computations to be NaN. The code for the bounds check has != missing, is this missing value the same as NaN?

**Comment by srherbener** [comment]
When ioda reads the netcdf fill value (9.9...e36) it replaces it with an internal missing value (-3.3...e38) so this might be why the filter is not working. We are converting to an internal set of missing values since we want these to be agnostic to different external conventions.

Is there a calculation on the height before the filter sees it? Not sure where the nan is coming from. If a nan is in the netcdf file, ioda should have changed it to the internal missing value.

I can help debug this if you want.

**Comment by CoryMartin-NOAA** [comment]
I think this might be more of a question of how to filter input for the UFO tests rather than IODA, as it's not clear to me that I have a filter set up properly as part of the 2m temp YAML file. My short term solution was to just remove this one location in the input file to test the UFO but I'd like to know how to filter as part of the test. Is there an example of a UFO test that first filters out "bad" observations?

**Comment by ytremolet** [comment]
It's only partially there at the moment. There is a check that ObsValue, ObsError and QC are well defined, but not other quantities that are not the same for all obs. 
The plan would be to add a query function to the operators to know what they need, and do a check on that list. That's the most generic and simple way I can think of. Unless somebody has another idea?

**Comment by CoryMartin-NOAA** [comment]
Ok I just wanted to make sure there wasn't anything I was doing wrong. That plan sounds good to me.

**Comment by srherbener** [comment]
All, the PR's connected to this issue have both been merged into develop. Does that mean this is resolved? Thanks!

**Comment by CoryMartin-NOAA** [comment]
@srherbener I think so.
