### ISSUE TITLE
Need to provide bias parameters from GSI run for the obs bias correction functionality

### ISSUE THREAD

**Issue by srherbener** [JCSDA/ioda-converters#181]
Xin is working on an implementation that adds observation bias correction to the cost function. His first step included reading bias parameters from GSI, thus the need to provide these in the GSI ncdiag files.

We need to agree in which file the bias parameters should be stored, and how to store these data (attributes, variables, etc.). Reading the bias parameters is a temporary solution. As I understand it, the bias parameters will ultimately be calculated on the fly in the bias correction code. The options for storing the bias parameters appear to be:
* obs file
* geovals file
* new bias parameters file

We also need to specify what is needed from GSI.

**Comment by srherbener** [comment]
I'm assuming that this will become a moot point once the "calculate bias coefficients on the fly" feature is merged in. Is this correct?

**Comment by srherbener** [comment]
@xinzhang8noaa, you don't need GSI bias correction parameters from GSI anymore, correct? In other words I should be able to close this issue.

**Comment by xinzhang8noaa** [comment]
Yes,  you can close, Thanks !
