### ISSUE TITLE
Add Travis-CI to ioda-converters repo

### ISSUE THREAD

**Issue by srherbener** [JCSDA/ioda-converters#182]
Travis-CI will run tests every time that a PR is submitted, and when commits are pushed to existing PRs.

We need to make sure that the ODB2 testing is enabled. Travis-CI runs on a Travis server and the process includes building the software stack, environment and the code being tested. We can enable ODB_API and include the ODB libraries for this process and thus get the ODB2 testing to run.

**Comment by srherbener** [comment]
The Travis-CI methodology and configuration for our repos is nearing completion (at least far enough to unleash it on all the repos). Once this step is completed, we can add Travis-CI to this repo.

**Comment by aerorahul** [comment]
I wonder if a `lite` software stack should be built for testing this repo.
All it needs is `python` with `pycodestyle`, which is standard with`anaconda`.  We should check if it is available in `miniconda`. Also required is  `nccmp` which in turn needs `gcc`, `hdf5`, `netcdf-c`.
One could (in theory) build `nccmp` from `anaconda` provided libraries for `gcc`, `netcdf`.

**Comment by srherbener** [comment]
Looks like I missed closing this. Travis-CI has been running in ioda-converters for a while now.
