### ISSUE TITLE
Skip using ExtractObsData for conventional obs from GSI diags

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA/ioda-converters#183]
After changing the looping order of the radiances, IODA observations now write fairly quickly, however the bottleneck for GSI diag conversions is now conventional obs such as aircraft. I believe, and @srherbener correct me if I'm wrong, that since the GSI diags are already formatted such that each lat, lon, obs, etc. are the same length, that we can bypass using ExtractObsData and just directly place everything into LocMdata, VarMdata, etc. like is done for the radiances class and then call BuildNetcdf

**Comment by srherbener** [comment]
If you've got the t,q,u,v values all lined up by location with missing values in the appropriate locations in the input file, then you should be able to skip ExtractObsData.

**Comment by CoryMartin-NOAA** [comment]
addressed in PR #187
