### ISSUE TITLE
station_elevation@MetaData has some strange values in satwind_obs_2018041500_m.nc4 (when viewed in xconv) air_pressure looks like strange as does height@MetaData. Similar issue in the _s version.

### ISSUE THREAD

**Issue by MarekWlasak** [JCSDA/ioda-converters#185]

**Comment by CoryMartin-NOAA** [comment]
@MarekWlasak which branch? develop? this is hopefully fixed in a pending pull request #184

**Comment by MarekWlasak** [comment]
This is in the  files: ioda/feature/use_pressure (which is soon to be in develop).  It could also affect develop, but I have not checked.

**Comment by CoryMartin-NOAA** [comment]
@shlyaeva (I think she's who added them there?) might need to re-generate the files for that branch once the ioda_converters are updated for station_elevation

**Comment by srherbener** [comment]
@MarekWlasak, it looks like this has been fixed with @CoryMartin-NOAA's latest PR merge containing the new set of GSI obs and geovals files. Please check and close this issue if you are satisfied with the new data. Thanks!
