### ISSUE TITLE
CMake build script for feature/gnssro-fortran-converter

### ISSUE THREAD

**Issue by markjolah** [JCSDA/ioda-converters#190]
Create CMake build script for [feature/gnssro-fortran-converter](https://github.com/JCSDA/ioda-converters/compare/feature/gnssro-fortran-converter)

Tasks:
 * Create: `FindBUFR.cmake`
 * Create `JCSDA/jedi-stack/buildscripts/libs/build_libbufr.sh`
 * Create test script

**Comment by markjolah** [comment]
I will assign this to myself.  I don't seem to have permission to do so.

**Comment by srherbener** [comment]
@markjolah, I've assigned you to this issue. Plus I fixed the permissions problem. You should have write access to this repo now (meaning you can assign, do PR's, push commits, etc.).

**Comment by srherbener** [comment]
@markjolah, can this issue be closed now? Thanks!

**Comment by markjolah** [comment]
Closed by #212
