### ISSUE TITLE
Add new file (obsdiag) containing diagnostic information from GSI for QC development in UFO

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA/ioda-converters#218]
There are obs and geoval files used in UFO for development.  To develop the capability of data quality control in UFO, information such as Jacobians from observation operator are required to implement the QC component in UFO.  Therefore, a separate file called obsdiag is created to store the required information.  In addition, tropopause pressure is also added into the existing geoval file.

**Comment by srherbener** [comment]
@emilyhcliu, is this issue closed now that UFO #219 has been merged? Thanks!

**Comment by emilyhcliu** [comment]
Yes, It should be closed.  I am closing it.  Thanks.
