### ISSUE TITLE
Build on cheyenne

### ISSUE THREAD

**Issue by jjguerrette** [JCSDA/ioda-converters#243]
I am having difficulty building on cheyenne.  I loaded the jedi/gnu-openmpi module, but ecbuild can not find the correct Python library:

```
-- [iodaconv] (0.0.0) [5fdc0f5]
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
CMake Error at /glade/u/apps/ch/opt/cmake/3.14.4/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "2.7.13")
Call Stack (most recent call first):
  /glade/u/apps/ch/opt/cmake/3.14.4/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /glade/u/apps/ch/opt/cmake/3.14.4/share/cmake-3.14/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /glade/work/miesch/modules/core/ecbuild/jcsda-3.1.0.jcsda2/share/ecbuild/cmake/ecbuild_find_python.cmake:203 (find_package)
  CMakeLists.txt:42 (ecbuild_find_python)
```

@mmiesch @hailingz is this a known problem on Cheyenne or am I doing something wrong?

@svahl991 and @junmeiban, maybe you have some idea from previous experience.

Here is my ecbuild command:
```
ecbuild --prefix=/glade/work/guerrett/pandac/build/ioda-converters/ /glade/work/guerrett/pandac/code/ioda-converters/
```

**Comment by mmiesch** [comment]
HI @jjguerrette - this is an issue we have been discussing - just today in fact.  The problem is that we cannot do a system install of python packages on an HPC system in such a way to make it accessible to everybody because we don't have admin privileges.  So, currently users have to install the requisite python packages on their own, in their own user space.  Eventually we'll provide comprehensive jedi python packages with dependencies for ioda-converters and other repos but we're not there yet.  For now, we recommend you do your own installation of the various python packages identified in [jedi-stack](https://github.com/JCSDA/jedi-stack/blob/61c19304cbb16818287851e93178134d3508bf68/buildscripts/libs/build_pyjedi.sh#L13).   Then, if you also want odyssey, you can install it in your own user space by cloning the jcdsa fork of odc and running this (make sure you first load the ecbuild, eckit, and odc modules):
~~~~~
ecbuild -DCMAKE_INSTALL_PREFIX=<install-dir> --build=Release <odyssey-dir>
make -j4
make install
~~~~~
Let us know if you have problems.

**Comment by jjguerrette** [comment]
It appears there is an alternative solution on cheyenne.  I ran ecbuild after loading the latest cheyenne module and entering the native NPL (NCAR Py Lib) environment:

```
module load python/3.7.5
source /glade/u/apps/ch/opt/usr/bin/npl/ncar_pylib.csh
```

That seems to work.

**Comment by mmiesch** [comment]
Thanks @jjguerrette - good to know.  I guess odyssey isn't required yet for the test suite.  Is that right @srherbener?

**Comment by srherbener** [comment]
Correct. However there is an optional build in develop for ODB files that is still dependent on the old odb-api library. This will be ported to the new odc/odyssey library soon. And there is a feature branch (nc2odb) that depends on odc/odyssey.

So, you are good for now without odc/odyssey, but it would be good for us to get those in place soon.

Thanks!

**Comment by srherbener** [comment]
@jjguerrette, in your example ecbuild command, it looks like you might be pointing the prefix into the build area. Running `make install` in this case could potentially break the build area. 

If I've got this right, you should pick another place to install that is outside your source and build areas. For example: `ecbuild --prefix=/glade/work/guerrett/pandac/install ...`.

**Comment by jjguerrette** [comment]
@srherbener, I'm a little confused about the `CMAKE_INSTALL_PREFIX` flag.  When I set it to a different directory ($HOME/tools), it looks like I get copies of `bin/     etc/     include/ lib/ ` in that directory with the correct local location of lib prescribed in the binaries.  Then I have those some directories/contents in the build directory with the correct local location (build directory) prescribed in the binaries.

Does one ever need to set `CMAKE_INSTALL_PREFIX`?  Is there a purpose for having a second copy of the binaries and libraries?  Maybe this is more relevant for compiled code...  Also, is there a difference between `--prefix=` and `-DCMAKE_INSTALL_PREFIX=`?

@mmiesch, regarding odyssey, I am confused on what this is and why I might need it.  Something to do with ODC?

**Comment by srherbener** [comment]
@jjguerrette, Sorry about the confusion. The build area gets `bin/ lib/ include/` directories for the purpose of building and testing programs/scripts that are part of that build. The install area mimics this, but is intended to be separate from the build area. This allows you to build, test and run `make install` providing all the data needed to use the libraries/programs/scripts that are part of your build without all the extra stuff (source code, test data/code, intermediate build files, etc). That way, you can remove the source and build area and the install area still stands on its own.

odc is a library for doing IO with ODB files and provides C and Fortran APIs. odyssey is a python API that provides IO with ODB files. odyssey uses the ODC library under the hood.

**Comment by jjguerrette** [comment]
Thank you for the explanation.  That all makes sense to me now.
