### ISSUE TITLE
gsi-ncdiag converter: Missing GsiHofX groups

### ISSUE THREAD

**Issue by markjolah** [JCSDA/ioda-converters#246]
Some of the ouput files from `gsi-ncdiag` converter are missing the `@GsiHofX` and associated groups like `@GsiHofXBc`.

In particular, the following files seem to be incomplete (there may be others):
* sst
* gps_bend,

Example of missing `@GsiHofX` variables
```
 ncdump -h sst_obs_2019070100.nc4 
netcdf sst_obs_2019070100 {
dimensions:
	nvars = 1 ;
	nlocs = 10672 ;
	nrecs = 993 ;
	nstring = 50 ;
	ndatetime = 20 ;
variables:
	int sea_surface_temperature@ObsType(nlocs) ;
	int sea_surface_temperature@PreUseFlag(nlocs) ;
	int sea_surface_temperature@GsiUseFlag(nlocs) ;
	float sea_surface_temperature@GsiQCWeight(nlocs) ;
	float sea_surface_temperature@GsiAdjustObsError(nlocs) ;
	float sea_surface_temperature@GsiFinalObsError(nlocs) ;
	float sea_surface_temperature@ObsValue(nlocs) ;
	float sea_surface_temperature@ObsError(nlocs) ;
	int sea_surface_temperature@PreQC(nlocs) ;
	char Station_ID@RecMetaData(nrecs, nstring) ;
	float time@MetaData(nlocs) ;
	char station_id@MetaData(nlocs, nstring) ;
	float latitude@MetaData(nlocs) ;
		string latitude@MetaData:units = "degrees_north" ;
	float longitude@MetaData(nlocs) ;
		string longitude@MetaData:units = "degrees_east" ;
	float station_elevation@MetaData(nlocs) ;
		string station_elevation@MetaData:units = "m" ;
	float air_pressure@MetaData(nlocs) ;
		string air_pressure@MetaData:units = "Pa" ;
	float height@MetaData(nlocs) ;
		string height@MetaData:units = "m" ;
	char datetime@MetaData(nlocs, ndatetime) ;
	int record_number@MetaData(nlocs) ;
	char variable_names@VarMetaData(nvars, nstring) ;
```

**Comment by emilyhcliu** [comment]
If any of the observation types is missing the GsiHofX, this means this particular data type has not been tested using the IODA file converted from GSI ncdiag file in UFO

**Comment by emilyhcliu** [comment]
The GNSSRO development is not using  GSI files for IODA.  The GNSSRO file you have now is directly generated from raw data from IODA format, and the GsiHofX reference is not included.

**Comment by emilyhcliu** [comment]
@markjolah @cyberbass The updated obs files for 2019070100 can be found on s4 at the following location: /data/users/eliu/AOP75/2019070100_new/obs

Things fixed in this updated data set are:
(1) Removed obsolete "nrecs" dimension from obs files 
(2) Added units to GSI reference variables (e.g., @GsiHofX)
(3) **Added  @GsiHofX and @GsiHofXBc for sea surface temperature in SSTS obs file**

Please let me know if this new set of obs files work for jedi-rapids.

**Comment by emilyhcliu** [comment]
@emilyhcliu @cyberbass GNSSRO data have not been tested and validated using ioda file converted from gsi ncdiag file. GNSSRO data is converted to IODA format directly from raw data.

**Comment by srherbener** [comment]
@cyberbass, @emilyhcliu, do you anticipate this getting completed in either April 2020 or May 2020. If so, please add the corresponding Milestone (OBS - April 2020, OBS - May 2020). Thanks!

**Comment by markjolah** [comment]
This is not longer relevent.  Reopen if it becomes so again.
