### ISSUE TITLE
Add ProdGSI variables to gsi-ncdiag converter

### ISSUE THREAD

**Issue by ilianagenkova** [JCSDA/ioda-converters#259]
Created ProdGSI/wind_vars branch (from feature/files_for_jedi) to add 3 satwind variables to GSI_diags/diag_conv_uv_ges.2018041500_ensmean.nc4 

Created ioda-convertesr branch to add 3 new satwind variables to ioda obs files:
origin/IGBG-ic-satwind
gsi_add_vars_uv = {
...
    'Errinv_Input': 'GsiInputObsError',
    'SWCM_spec_type': 'SpectralType',
    'SAZA_sat_zen_angle': 'SatZenAngle',
    'SCCF_chan_wavelen': 'ChanWavelen',
...
}

**Comment by ilianagenkova** [comment]
Renamed branch IGBG-ic-satwind to feature/ic-satwind to comply with Git-Flow naming conventions.

**Comment by emilyhcliu** [comment]
@ilianagenkova Do you have the output file generated on HERA?  To begin with, we can check if the variables you need are in the output file.

**Comment by srherbener** [comment]
@ilianagenkova, the next step would be to make a pull request (PR) out of the branch you created and ask some of us to review it.

Before creating the PR, you will likely need to update the test with a new "expected results" netcdf file. I believe that is the file that @emilyhcliu is asking about. I can help you get the new file installed in the proper place.

Thanks!

**Comment by ilianagenkova** [comment]
@emilyhcliu 
The GSI (diag_conv_uv_*) and ioda-converter (satwind_*) output files are in:
/scratch2/NCEPDEV/stmp1/Iliana.Genkova/JEDI_conv/output/2018041500/
I copied the new _obs_ files to /testinput_tier_1 already and confirmed that the ufo satwind tests completed ok.

@srherbener 
Which test needs to be updated? The bundle that goes on S3? 

I'll wait for your comments before I create a PR. 
thanks!

**Comment by srherbener** [comment]
@ilianagenkova, I was referring to updating a test in ioda-converters. I was assuming that there was a test in ioda-converters for the GSI ncdiag satwind obs type, but I just checked and there isn't one.

There do exist two tests for the GSI ncdiag converters, one for conventional obs (surface virtual temperature) and one for radiance (amsua, aqua). There is a tradeoff between testing every possible obs type (very high code coverage, but a lot of redundant coverage) versus having a few tests that cover a lot of the code (short test runtime). The two existing tests are probably enough to catch most cases where an update breaks the GSI converters so I would lean toward not adding a new test for satwind.

If you want to add a test for satwind, that would be fine as long as you can find a test case that runs fast (say 10-100 observation values). However, I'm okay issuing the PR without a new test.

**Comment by ilianagenkova** [comment]
@emilyhcliu 
Now there are
/test/testinput/gsidiag_conv_uv_testinput.nc
/test/testoutput/satwind_obs_2018041500.nc4 
committed with the branch.

@srherbener and @CoryMartin-NOAA 
/test/CMakeLists.txt  is updated to add test_iodaconv_gsidiag_conv_uv

**Comment by CoryMartin-NOAA** [comment]
@ilianagenkova great! I look forward to the upcoming PR to review.

**Comment by srherbener** [comment]
@ilianagenkova, sounds great! I tried your branch on my iMac and the test passed so it looks good.

It looks like you you need to merge develop into your feature/ic-satwind branch. Then you should be all synced up and ready to submit the PR.

Thanks for taking care of this!

**Comment by ilianagenkova** [comment]
@CoryMartin-NOAA , @srherbener and @emilyhcliu ,
 
First off,  I had to update ProdGSI one last time (changes already pushed into feature/files_for_jedi) to extract more satwind BUFR variables.

Now gsi_ncdiag.py has two updated dictionaries:
all_LocKeyList = {
    ...
    'SWCM_spec_type': ('satwind_spectral_type', 'float'),
    'SAZA_sat_zen_angle': ('sensor_zenith_angle', 'float'),
    'SCCF_chan_wavelen': ('channel_wavelength', 'float'),
    'QI_with_FC': ('satwind_quality_ind_with_fc', 'float'),
    'QI_without_FC': ('satwind_quality_ind_no_fc', 'float'),
}

and 
gsi_add_vars_uv = {
...
'Errinv_Input': 'GsiInputObsError',
...
}

I updated the test files:
/test/testinput/gsidiag_conv_uv_testinput.nc
/test/testoutput/satwind_obs_2018041500.nc4
 and
test_iodaconv_gsidiag_conv_uv passed OK. 

As of this moment feature/ic-satwind has all my changes and is in sync with /develop.
