### ISSUE TITLE
ctest failed for test_iodaconv_ncep_bufr

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA/ioda-converters#287]
@CoryMartin-NOAA @srherbener 

I checked out the latest ioda-converters.  The build was OK, but ctest failed for test_iodaconv_ncep_bufr.

The error message is:
```
Traceback (most recent call last):
File "/scratch1/NCEPDEV/da/Emily.Liu/JEDI-GSI/ioda-converters/build/bin/ncep_classes.py", 
line 3, in <module> import ncepbufrModuleNotFoundError: 
No module named 'ncepbufr'1/1 Test #23:
test_iodaconv_ncep_bufr ..........***Failed    0.61 sec
```

The previous version also uses "import ncepbufr"  and it built without a problem.   

I am wondering if you also see the same problem?

**Comment by srherbener** [comment]
@emilyhcliu, I'm going to be on vacation this week so hopefully @mmiesch may be available to help. This is working on my Mac and in the containers so I'm not sure what has changed.

I suspect that either ncepbufr got moved/removed or PYTHONPATH is not getting set properly. Python can find packages in standard locations (such as /usr/local/lib) but if a package is not in a standard location, PYTHONPATH needs to be set for Python to be able to find the package.

**Comment by CoryMartin-NOAA** [comment]
I agree with @srherbener , it seems like a python installation issue. Which version are you using? Is this on Hera?

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA Thanks for looking into this.
I am using the following for python:

```
module use -a /contrib/anaconda/modulefiles
module load anaconda/latest
```

**Comment by CoryMartin-NOAA** [comment]
Hmmm, Try Jong's Anaconda install:
module use -a /scratch2/NCEPDEV/marineda/Jong.Kim/save/modulefiles/

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA 
As you suggested, I use Jong's install:
```
module use -a /scratch2/NCEPDEV/marineda/Jong.Kim/save/modulefiles
module load anaconda/3.15.1
```
That works!!  Thank you so much~~
I have another question about the module use for GSI.  I will open an issue there.
