### ISSUE TITLE
SSS convertors longitude shift

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA/ioda-converters#303]
SSS files longitudes are in the range of 0 to 360 degree. We are going to convert them to -180 to 180  to be consistent with the Gaussian filtering

**Comment by jjguerrette** [comment]
Just to save you some time, if you are talking about the `Gaussian_Thinning` filter, then it was updated in the below PR to work with either convention.

https://github.com/JCSDA/ufo/pull/1135

**Comment by HamidehGMAO** [comment]
Sounds great! Thanks a lot @jjguerrette
