### ISSUE TITLE
Cmake update for `feature/bufr-converter`

### ISSUE THREAD

**Issue by markjolah** [JCSDA/ioda-converters#313]
This package no longer is ecbuild-based.   The `feature/bufr-converter` is a C++ package which was depending on ecbuild and will need to be refactored to work in standard CMake.

**Comment by markjolah** [comment]
@aerorahul @rmclaren I will not have time to visit this issue until next week.  In the meantime you can probably keep working in the branch as it exists.  I will submit a PR against it.

**Comment by aerorahul** [comment]
> @aerorahul @rmclaren I will not have time to visit this issue until next week. In the meantime you can probably keep working in the branch as it exists. I will submit a PR against it.

Thanks @markjolah Next week or the week after is fine.
