### ISSUE TITLE
Include surface height with AMSU-A obs type

### ISSUE THREAD

**Issue by srherbener** [JCSDA/ioda-converters#52]
Clara has built a new AMSU-A data set that includes surface height.

Anna is picking up the GSI flow and will be regenerating AMSU-A. Perhaps it's best to wait until Anna gets a result. Then we can check that surface height is included.

**Comment by srherbener** [comment]
@shlyaeva, the amsua files in the ioda repo have "height@MetaData". It looks like Cory changed this to "height_above_mean_sea_level@Metadata". Is this the surface height?

**Comment by CoryMartin-NOAA** [comment]
@srherbener I think it is surface height. Sorry, I changed it to conform to one of the CF-standard variable names.

**Comment by srherbener** [comment]
@CoryMartin-NOAA I'm just checking to see if this can be closed. We should be using the CF-standard name so let's leave it as you have it. Sorry about the confusion.

Sounds like I can close this issue
