### ISSUE TITLE
Utility to Convert VIIRS AOD netCDF files from NESDIS/CLASS to IODA netCDF format

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA/ioda-converters#77]
May also include thinning/superobbing capabilities depending on downstream availability

**Comment by coryrmartin** [comment]
See branch feature/viirs2ioda for progress

**Comment by srherbener** [comment]
@CoryMartin-NOAA, did your latest PR merge containing the new obs and geovals files resolve this issue? Thanks!

**Comment by CoryMartin-NOAA** [comment]
@srherbener no, this is a fortran utility to convert the raw, large VIIRS files for work for @mpagowski and myself. I should be able to add this though soon with another pull request. Probably next week.

**Comment by srherbener** [comment]
@CoryMartin-NOAA, sounds good. We can leave this open.

**Comment by srherbener** [comment]
@CoryMartin-NOAA, do you anticipate this getting completed in either April 2020 or May 2020. If so, please add the corresponding Milestone (OBS - April 2020, OBS - May 2020). Thanks!
