### ISSUE TITLE
Bug at def bufr_float_to_actual?

### ISSUE THREAD

**Issue by flampouris** [JCSDA/ioda-converters#84]
Instead of using the NetCDF variable names for the time, the BUFR variable names should be used because the BUFR variable names are relatively constant. The NetCDF ones are user-defined...

At line 403 of the source code of bufr2ncObsTypes.py, instead of:

OutVals[VarSpec[0]] = BufrFloatToActual(Bval, VarSpec[2]) 

the code should be:

OutVals[VarSpec[1]] = ...

Otherwise, at the def calc_obs_date_time -and not only- for the transformation of the time the function will probably fail.

**Comment by flampouris** [comment]
A new branch is created (bugfix/ValSpec-sf), with the update. It is tested successfully with two examples.

**Comment by srherbener** [comment]
Hi @flampouris, is this issue resolved now?

**Comment by flampouris** [comment]
yes
