### ISSUE TITLE
Marine CS - Unified converted from BUFR to NC4 for all the observations that have the BUFR table embedded.

### ISSUE THREAD

**Issue by flampouris** [JCSDA/ioda-converters#86]
During the dumping to the observations tanks, NCEP adds the BUFR tables.

The unified converter reads the tables from the observation files, creates a dictionary from BUFR to NC and uses it to convert them to NC4.

This piece of code is built on top of the bufr2nc.py example and it will probably replace everything else.

**Comment by flampouris** [comment]
@srherbener and @svahl991 

We ( @DeannaSpindler mainly ) created the ncep_classes.py (see the feature/ncepAllobs branch).  It's one class that almost all the information that is needed for importing the observations is some kind of variable, retrievable from the observation files. 

The main advantage of this example that we won't need any other classes for any observation in BUFR or prepBUFR format.

Currently, it has one issue with the nc_writer, but as this function will be updated, I didn't try to solve it. 

Also, there are a few TODOs, but there are not essential for now.

**Comment by srherbener** [comment]
@flampouris, @DeannaSpindler and @svahl991 

If I understand what you've done, it looks like you dump out the BUFR table information which contains the variables, units, descriptions etc. and use that to form the list of items you want to convert (by calling the existing conversion method in bufr2nc.py). And the idea here is by using this BUFR table process, there is no need to add more classes to the set that already exists in bufr2nc.py.

I think this is a great approach, and a big improvement over the existing code. Thanks for doing this!

We can discuss and develop this further during next week's code sprint. Looking forward to working with you on this.
